---
title: "linear_models"
author: "Congyang Xie"
date: "11/29/2021"
output: github_document
---
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(p8105.datasets)
```

```{r}
data("nyc_airbnb")

nyc_airbnb <-
  nyc_airbnb %>%
  mutate(stars = review_scores_location / 2) %>%
  rename(borough = neighbourhood_group) %>%
  filter(borough != "Staten Island") %>%
  select(price, stars, borough, neighbourhood, room_type)
  
```

## fit a model

```{r}

nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) + 
  geom_point()
```

```{r}

fit = lm(price ~ stars + borough, data = nyc_airbnb)
```
look at the result
```{r}
fit

summary(fit)
```

```{r}

broom::glance(fit)

broom::tidy(fit) %>% 
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>% 
  knitr::kable(digits = 3)
```

## Be in control of factors

```{r}
nyc_airbnb <- 
  nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  )
```

look at the plot again

```{r}

nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough))+
  geom_point()
```

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb) 

broom::tidy(fit) %>% 
  mutate(term = str_replace(term, "borough", "Borough: "))

broom::glance(fit) 
```

## diagnostics

```{r}

modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = borough, y = resid))+
  geom_violin()+
  ylim(-500, 1500)
```

```{r}

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid)) + 
  geom_point() + 
  facet_wrap(. ~ borough)
```

## Hypothesis test

```{r}
# t-test by default
fit %>% 
  broom::tidy()
```

what about the significance of borough

```{r}
fit_null = lm(price ~ stars, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough, data = nyc_airbnb)

anova(fit_null, fit_alt) %>% 
  broom::tidy()
```

## nest datam fit models

```{r}
fit = lm(price ~ stars * borough + room_type * borough, data = nyc_airbnb)

broom::tidy(fit)
```

```{r}
nest_lm_res <-
  nyc_airbnb %>%
  nest(data = -borough) %>%
  mutate(models = map(data, ~ lm(price ~ stars + room_type, data = .x)),
         results = map(models, broom::tidy)) %>%
  select(-data, -models) %>%
  unnest()
```

```{r}


nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  nest(-neighbourhood) %>% 
  mutate(models = map(data, ~ lm(price ~ stars + room_type, data = .x)),
         results = map(models, broom::tidy)) %>%
  select(-data, -models) %>%
  unnest(results) %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighbourhood, y = estimate)) +
  geom_point()+
  facet_wrap(. ~ term) +
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

